spring:
  cache:
    cache-names: content, comment, person, personContent, profile, rating, view
    caffeine:
      spec: maximumSize=100, expireAfterAccess=30m
app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/KinoBase
      password: '1234'
      username: postgres
      maximum-pool-size: 15
server:
  error:
    include-binding-errors: always
    include-message: always
security:
  jwt:
    secret: aXJnZXVqaGFpdWhyZ2lodWpyZ2F1cmdpaGRqb2lqa2Fsc2RyZ2lraGFzaW91a2pyaGdhb2k7a3Nncmg=
    access: 3600000
    refresh: 2592000000
springdoc:
  override-with-generic-response: false